name: delete-github-repository-secrets-using-workflow
on:
  workflow_dispatch:
    inputs:
      organization:
        type: string
        default: 'devwithkrishna'
        description: 'The GitHub organization where the Secret will be delted from.'
        required: true
      repository_name:
        type: string
        description: 'Repository from which secret to be deleted'
        required: true
      secret_name:
        type: string
        description: "Secret name to delete from org"
        required: true

run-name: ${{ github.actor }} deleting secret ${{ inputs.secret_name }} from ${{ inputs.repository_name }}
jobs:
  delete-github-repository-secrets-using-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: package installations
        run: |
          pip install pipenv
          pipenv install
      - name: delete github org secret
        env:
          GH_TOKEN: ${{ secrets.DEVWITHKRISHNA_PERSONAL_ACCESS_TOKEN }}
          repository_name: ${{ inputs.repository_name }}
          secret_name: ${{ inputs.secret_name }}
          organization: ${{ inputs.organization }}
        run: |
          pipenv run python3 delete_repo_secret.py 
          echo "Secret deleted"
      - name: Completed
        run: |
          echo "program completed successfully"